### PR TITLE
More exciting and exotic types

### PR DESCRIPTION
**Pull request by loovjo**
I thought the types the random button generated were a little bit boring so I added some more, nested types

### CODE REVIEW

**Comment by loovjo** [comment]
The commits are squashed and the types have a maximum recursion limit of two nested types (such as `Result<Vec<_>, _>`. Is there anything else to consider before merging?

**Comment by jplatte** [comment]
> Is there anything else to consider before merging?

Nope.

Thanks! :)

**Comment by jplatte** [comment]
Whoops, wrong button :man_facepalming:

**Comment by jplatte** [comment]
I hate GitHub. Rebasing still changes the committer even if the rebase is a no-op.

**Comment by jplatte** [comment]
So I don't have any automatic deployment in place, if you're wondering why the changes aren't reflected on the website. I'll deploy in the next few days.

**Pull request merged**
